apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
{{ include "pgbouncer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: pgbouncer
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.pgbouncer.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "pgbouncer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}